[2024-09-20T23:23:55.089+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-20T23:23:55.332+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Bitcoin_ETL.data_load manual__2024-09-20T23:23:37.416370+00:00 [queued]>
[2024-09-20T23:23:55.343+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Bitcoin_ETL.data_load manual__2024-09-20T23:23:37.416370+00:00 [queued]>
[2024-09-20T23:23:55.344+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 6
[2024-09-20T23:23:55.369+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): data_load> on 2024-09-20 23:23:37.416370+00:00
[2024-09-20T23:23:55.378+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=115) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-20T23:23:55.380+0000] {standard_task_runner.py:72} INFO - Started process 118 to run task
[2024-09-20T23:23:55.381+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'Bitcoin_ETL', 'data_load', 'manual__2024-09-20T23:23:37.416370+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/API_Crypto_Extraction_modularizad.py', '--cfg-path', '/tmp/tmp3kyx7wsk']
[2024-09-20T23:23:55.385+0000] {standard_task_runner.py:105} INFO - Job 16: Subtask data_load
[2024-09-20T23:23:55.445+0000] {task_command.py:467} INFO - Running <TaskInstance: Bitcoin_ETL.data_load manual__2024-09-20T23:23:37.416370+00:00 [running]> on host 9c12df3acb7b
[2024-09-20T23:23:55.539+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='francogranieri56@gmail.com' AIRFLOW_CTX_DAG_OWNER='FrancoGranieri' AIRFLOW_CTX_DAG_ID='Bitcoin_ETL' AIRFLOW_CTX_TASK_ID='data_load' AIRFLOW_CTX_EXECUTION_DATE='2024-09-20T23:23:37.416370+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-20T23:23:37.416370+00:00'
[2024-09-20T23:23:55.541+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-20T23:23:55.569+0000] {logging_mixin.py:190} INFO - data file path /opt/***/dags/tmp_files/data2024-09-20 23:23:53.274946.csv
[2024-09-20T23:23:55.611+0000] {logging_mixin.py:190} INFO - CSV data                                             id_date  ...                   date_time
0                bitcoin-2024-09-20 23:23:53.252506  ...  2024-09-20 23:23:53.252506
1               ethereum-2024-09-20 23:23:53.252506  ...  2024-09-20 23:23:53.252506
2                 tether-2024-09-20 23:23:53.252506  ...  2024-09-20 23:23:53.252506
3           binance-coin-2024-09-20 23:23:53.252506  ...  2024-09-20 23:23:53.252506
4                 solana-2024-09-20 23:23:53.252506  ...  2024-09-20 23:23:53.252506
..                                              ...  ...                         ...
95  golem-network-tokens-2024-09-20 23:23:53.252506  ...  2024-09-20 23:23:53.252506
96                  dash-2024-09-20 23:23:53.252506  ...  2024-09-20 23:23:53.252506
97                  holo-2024-09-20 23:23:53.252506  ...  2024-09-20 23:23:53.252506
98                aragon-2024-09-20 23:23:53.252506  ...  2024-09-20 23:23:53.252506
99                  just-2024-09-20 23:23:53.252506  ...  2024-09-20 23:23:53.252506

[100 rows x 5 columns]
[2024-09-20T23:23:57.081+0000] {logging_mixin.py:190} INFO - se va a insertar la table francogranieri56_coderhouse.cripto_price_new_data
[2024-09-20T23:23:57.421+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/API_Crypto_Extraction_modularizad.py", line 113, in cargar_data
    cur.execute(truncate_table_query)
psycopg2.errors.UndefinedTable: relation "francogranieri56_coderhouse.cripto_price_new_data" does not exist

[2024-09-20T23:23:57.447+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=Bitcoin_ETL, task_id=data_load, run_id=manual__2024-09-20T23:23:37.416370+00:00, execution_date=20240920T232337, start_date=20240920T232355, end_date=20240920T232357
[2024-09-20T23:23:57.469+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/email.py:155: RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2024-09-20T23:23:57.469+0000] {email.py:272} INFO - Email alerting: attempt 1
[2024-09-20T23:23:58.605+0000] {email.py:283} INFO - Sent an alert email to ['francogranieri56@gmail.com']
[2024-09-20T23:24:00.039+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-20T23:24:00.040+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 16 for task data_load (relation "francogranieri56_coderhouse.cripto_price_new_data" does not exist
; 118)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/API_Crypto_Extraction_modularizad.py", line 113, in cargar_data
    cur.execute(truncate_table_query)
psycopg2.errors.UndefinedTable: relation "francogranieri56_coderhouse.cripto_price_new_data" does not exist

[2024-09-20T23:24:00.063+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-20T23:24:00.087+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-20T23:24:00.090+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
